// <auto-generated />
namespace CRUD_Using_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(status));
        
        string IMigrationMetadata.Id
        {
            get { return "201511071742340_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
